### ISSUE TITLE
Add missing contractPerformance values

### ISSUE THREAD

**Issue by nbundi** [actusfrf/actus-dictionary#12]
following values are missing:
- matured: the contract has matured
- terminated: the contract has been terminated

**Comment by nbundi** [comment]
also
- exercised: for american type options

**Comment by nbundi** [comment]
problem: exercised can be in conflict with delayed, delinquent, default as on an exercise event follows a settlement event which represents a payment obligation. if the obligation is not settled on time then contractPerformance transitions from exercised to e.g. delayed. however, once in delayed, where do we transition to if the obligation is settled?

**Comment by jo-es** [comment]
Has to be added to State definitions as well

**Comment by nbundi** [comment]
Thanks @jo-es, missed that one but will fix
